# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 03:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20160919_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='todo',
            name='username',
            field=models.CharField(default='', max_length=200),
        ),
    ]
