# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-28 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20160920_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='done',
        ),
    ]
